### ISSUE TITLE
Coverage ignore hints not working for export

### ISSUE THREAD

**Issue by einarq** [istanbuljs/istanbuljs#297] opened 2019-02-18 13:52 UTC
After upgrading to Babel 7, our ignore hints are no longer working like they used to. 
In my case a lot of it (the hints not working) seems to be related to ignoring the export directly.

This does not get ignored:
```
/* istanbul ignore next */
export default function MyFunction () {
}
```

This gets ignored fine:
```
/* istanbul ignore next */
function MyFunction () {
}
export default MyFunction;
```

Possible related issues:
https://github.com/istanbuljs/istanbuljs/issues/157
https://github.com/istanbuljs/istanbuljs/issues/162
https://github.com/istanbuljs/babel-plugin-istanbul/issues/150

**Comment by coreyfarrell** [comment] 2019-02-18 16:45
I can confirm this issue and have posted what I believe will fix it.  I'm not sure this is related to any of the issues you linked.

**Comment by einarq** [comment] 2019-02-18 17:25
> I can confirm this issue and have posted what I believe will fix it. I'm not sure this is related to any of the issues you linked.

Thanks! No that may very well be the case, it was just a hunch. Thanks for the quick reply. Any idea when it might be merged and released?

**Comment by coreyfarrell** [comment] 2019-02-18 17:33
> Any idea when it might be merged and released?

Hopefully won't take too long though I want to make sure that the tests I added adequately cover this change before it's merged.  This fix is at the lowest level of istanbul so this involves some risk.

**Comment by einarq** [comment] 2019-02-18 17:34
Btw, is there a way I could verify this locally before you merge it? Tried locating the file that was changed in the PR, but I don't have istanbul-lib-instrumenter in my node_modules folder.
Will the PR result in a new version of babel-plugin-istanbul? I guess that's my main dep., that and babel-istanbul (0.12.2). Not sure who does what... 
I also have karma-coverage-istanbul-reporter (2.0.4)

**Comment by coreyfarrell** [comment] 2019-02-18 17:53
You should have an `istanbul-lib-instrument` in your node_modules, there is no istanbul-lib-instrumenter.  istanbul-lib-instrument is a bit difficult due to it having a build step, you can't just edit the source.  You can do the following:
```sh
git clone https://github.com/coreyfarrell/istanbuljs/ -b ignore-next-export
cd istanbuljs
npm install
npx lerna --scope istanbul-lib-instrument exec npm pack
```
This will create `packages/istanbul-lib-instrument/istanbul-lib-instrument-3.1.0.tgz` which you can install by create a package.json dependency in your project for `"istanbul-lib-instrument": "file:path/to/istanbul-lib-instrument-3.1.0.tgz"`.  Once you add the dependency to your package.json I'd suggest clearing your node_modules and running `npm install`.

`babel-istanbul` is deprecated, most likely you should not be using that module.  `babel-plugin-istanbul` and `karma-coverage-istanbul-reporter` both use semver caret ranges so they should automatically pull the new `istanbul-lib-instrument` when released.

**Comment by einarq** [comment] 2019-02-18 18:42
Hm, didnt help:
I did this:
- generated tgz file using your steps
- added this line to my package.json file under devDeps
"istanbul-lib-instrument": "file:/work/istanbuljs/packages/istanbul-lib-instrument/istanbul-lib-instrument-3.1.0.tgz",
- did another npm install in my app directory
- ran the tests to generate coverage

No difference, I can see lines like these still not getting ignored. Perhaps I did something wrong? Pretty sure the npm install would not have worked if I didnt have the tgz file path correct, I had to adjust te path a couple of times before it went through.

```
/* istanbul ignore next */
export const getLaunchOptions = state => fromLaunchOptions.getLaunchOptions(state.launchOptions);
```

**Comment by coreyfarrell** [comment] 2019-02-18 18:55
What is the output of `npm ls istanbul-lib-instrument`?  Also `find node_modules -name istanbul-lib-instrument`

**Comment by einarq** [comment] 2019-02-18 19:01
$ npm ls istanbul-lib-instrument
SurveyDesigner@0.0.1 c:\dev\surveydesigner
+-- babel-plugin-istanbul@5.1.0
| `-- istanbul-lib-instrument@3.1.0  deduped
+-- istanbul-lib-instrument@3.1.0
+-- jest@24.1.0
| `-- jest-cli@24.1.0
|   `-- istanbul-lib-instrument@3.1.0  deduped
+-- karma-coverage-istanbul-reporter@2.0.4
| `-- istanbul-api@2.1.1
|   `-- istanbul-lib-instrument@3.1.0  deduped
`-- nyc@13.0.1
  `-- istanbul-lib-instrument@2.3.2

**Comment by einarq** [comment] 2019-02-18 19:03
`$ find node_modules -name istanbul-lib-instrument
node_modules/istanbul-lib-instrument
node_modules/nyc/node_modules/istanbul-lib-instrument
`

**Comment by einarq** [comment] 2019-02-18 19:04
So I guess it resolves to the wrong version due to nyc

**Comment by coreyfarrell** [comment] 2019-02-18 19:05
Can you update `nyc` to 13.3.0?  `nyc@13.0.1` depends on `istanbul-lib-instrument@2.x` so this might be causing problems.

**Comment by coreyfarrell** [comment] 2019-02-18 19:10
Also please verify you see the `ExportNamedDeclaration: entries()` when you run this grep:
```sh
$ grep node_modules/istanbul-lib-instrument/dist/visitor.js -e '\sExportNamed'
  ExportNamedDeclaration: entries(),
```

**Comment by einarq** [comment] 2019-02-18 19:17
Ok, upgraded nyc, now I have:

```
$ npm ls istanbul-lib-instrument
SurveyDesigner@0.0.1 c:\dev\surveydesigner
+-- babel-plugin-istanbul@5.1.0
| `-- istanbul-lib-instrument@3.1.0  deduped
+-- istanbul-lib-instrument@3.1.0
+-- jest@24.1.0
| `-- jest-cli@24.1.0
|   `-- istanbul-lib-instrument@3.1.0  deduped
+-- karma-coverage-istanbul-reporter@2.0.4
| `-- istanbul-api@2.1.1
|   `-- istanbul-lib-instrument@3.1.0  deduped
`-- nyc@13.3.0
  `-- istanbul-lib-instrument@3.1.0  deduped
```

```
$ find node_modules -name istanbul-lib-instrument
node_modules/istanbul-lib-instrument
```

```
grep node_modules/istanbul-lib-instrument/dist/visitor.js -e '\sExportNamed'
  ExportNamedDeclaration: entries(),
```

Still same coverage output though.

**Comment by coreyfarrell** [comment] 2019-02-18 19:31
Will need to see a repository demonstrating the error before I can provide any further help.

**Comment by einarq** [comment] 2019-02-18 19:36
Ok, I'll try to create that in the next few days. Will you still release the fix you have created already?

**Comment by coreyfarrell** [comment] 2019-02-18 20:17
We'll see how long it takes to get reviewed.  I can say for certain #298 fixes the issue in isolation.  What is preventing the fix from working in your specific situation I can't say yet.

**Comment by einarq** [comment] 2019-02-18 20:18
Ok. Could there be something related to the reporters? Or could I need a newer version of babel perhaps?
Thanks for all the help btw, really appreciated.

**Comment by coreyfarrell** [comment] 2019-02-18 20:23
Like I said I need to see a repo which reproduces the issue before I can know more.

**Comment by einarq** [comment] 2019-02-18 20:56
Weird. I deleted the whole node_modules folder, upgraded some more deps like @babel/core (7.2.2 to 7.3.3), and now your fix works! Tried downgrading babel/core again, didn't make a difference, fix still works. 
Go figure :) Anyway, fix looks good for me too then.

**Closed** 2019-02-18 22:26 UTC

**Comment by einarq** [comment] 2019-03-05 07:49
Seems this isn't released yet, right?

**Comment by coreyfarrell** [comment] 2019-03-05 14:24
It isn't, we have some other issues that need to be addressed before we can perform a release.  I've just created #318 which you can watch for release progress updates.

**Comment by Goran216** [comment] 2019-08-22 09:28
@einarq I tried your suggestion but still no luck. I can't use /* istanbul ignore next */

Any idea?
