### ISSUE TITLE
TS shorthand class properties using `super()` lead to invalid code

### ISSUE THREAD

**Issue by Swatinem** [istanbuljs/istanbuljs#237] opened 2018-11-12 19:30 UTC
Example:
```ts
abstract class A {}
export class B extends A {
  constructor(public p: string) {
    super();
  }
}
```

Istanbul Output:
```js
class A {}

class B extends (A) {
  constructor(p) {
    this.p = p;
    cov_wvdachw5s.f[0]++;
    cov_wvdachw5s.s[0]++;
    super();
  }
}
```

When I run this code, it fails with:

    ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

As a reference, babel 7 alone without the `istanbul` plugin generates correct code:
```js
class A {}

class B extends A {
  constructor(p) {
    super();
    this.p = p;
  }
}
```

**Comment by rsuk** [comment] 2018-12-07 17:18
I'm pretty sure I would be out of my depth, but if anyone has any ideas where in the codebase might be responsible for this issue I would love to have a dig around - this issue is really causing me some pain now.

**Comment by toolness** [comment] 2019-02-28 02:20
After much investigation, I found that my test suite was also failing due to this bug, so I guess it's still a problem as of the latest version of Istanbul (or whatever version of it ships with jest 24.1.0--there appear to be so many modules with the word `istanbul` in my lockfile that I have no idea what "version" of Istanbul I actually have).

**Comment by SimenB** [comment] 2019-02-28 14:15
@bcoe @coreyfarrell is this something you could look into? ❤️

**Comment by coreyfarrell** [comment] 2019-02-28 15:34
@SimenB I think I've found the source if this error.  Thanks to @jlmessenger for the reproduction instructions at https://github.com/istanbuljs/babel-plugin-istanbul/issues/185.

See https://github.com/babel/babel/blob/208195f42576a70798cedf1abe4d9f1d86979fcc/packages/babel-plugin-transform-typescript/src/index.js#L201-L212

It appears that `@babel/plugin-transform-typescript` fails to see the `super()` if it's not the first statement.
```js
abstract class A {}
export class B extends A {
  constructor(public p: string) {
    console.log('about to call super()');
    super();
  }
}
```

This snippet is incorrectly translated without using istanbul:
```js
class A {}

export class B extends A {
  constructor(p) {
    this.p = p;
    console.log('about to call super()');
    super();
  }

}
```

I don't think this can be fixed via istanbul, I've posted babel/babel#9609.

**Comment by coreyfarrell** [comment] 2019-07-04 15:02
I believe this issue should be fixed by the release of babel 7.5.0.  Can anyone confirm that the issue is resolved by running `npm update` on your repository?

**Comment by toolness** [comment] 2019-07-05 16:36
Hey, I just upgraded and I believe this is working.  Thank you for the fix!!!

**Comment by coreyfarrell** [comment] 2019-07-05 16:46
@toolness Thank you for confirming!

**Closed by coreyfarrell** 2019-07-05 16:46 UTC
