### ISSUE TITLE
Problem with generating cobertura report when running karma tests in parallel

### ISSUE THREAD

**Issue by abhi2495** [istanbuljs/istanbuljs#561] opened 2020-05-05 20:02 UTC
When karma is configured to run in parallel using the following config:
`
....
frameworks                : ['parallel', 'jasmine', 'intl-shim'],
...
parallelOptions           : {
      executors             : (require('os').cpus().length - 1),
      shardStrategy         : 'round-robin',
      aggregatedReporterTest: /istanbul/i
    },
....
`

and istanbul reporter is being used :

`
coverageIstanbulReporter  : {
      reports                : ['html', 'json-summary', 'cobertura'],
      dir                    : path.join(__dirname, '../../build/reports/karma/coverage'),
      combineBrowserReports  : true,
      fixWebpackSourcePaths  : true,
      skipFilesWithNoCoverage: true,
      'report-config'        : {
        html: {
          subdir: 'html'
        }
      },
      thresholds             : {
        emitWarning: true,
        global     : {
          statements: 95,
          lines     : 75,
          functions : 75,
          branches  : 75
        }
      },
      verbose                : false
    }
`

Then getting the following error:

`
(node:89296) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
    at Object.entries.forEach (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-reports/lib/cobertura/index.js:102:30)
    at Array.forEach (<anonymous>)
    at CoberturaReport.onDetail (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-reports/lib/cobertura/index.js:92:31)
    at Visitor.value (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at getChildren.forEach.child (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:92:19)
    at Array.forEach (<anonymous>)
    at ReportNode.visit (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:91:28)
    at getChildren.forEach.child (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:92:19)
    at Array.forEach (<anonymous>)
    at ReportNode.visit (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:91:28)
    at ReportTree.visit (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/istanbul-lib-report/lib/tree.js:127:24)
    at config.reporting.reports.forEach (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:220:12)
    at Array.forEach (<anonymous>)
    at writeReports (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:217:30)
    at createReport (/Users/1025453/codes/jda-azure-repos/dynamic-task-web-app/frontend/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:125:5)
(node:89296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

Versions used:
    "karma": "1.3.0",
    "karma-chrome-launcher": "3.1.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-coverage-istanbul-reporter": "^3.0.0",
    "karma-webpack": "1.8.0",
    "karma-parallel": "0.3.1",

**Comment by coreyfarrell** [comment] 2020-05-05 20:09
istanbuljs does not provide any karma plugins.  The bug you are experiencing has been fixed in the current version of istanbuljs libraries, unfortunately `karma-coverage-istanbul-reporter` is not using the current version of our libraries.  My recommendation is that you should use `karma-coverage` 2.x instead.  Again karma-coverage is not an official istanbuljs module however it does appear to be more actively maintained and is open to bug reports from open source users.

**Closed by coreyfarrell** 2020-05-05 20:09 UTC

**Comment by coreyfarrell** [comment] 2020-05-06 14:54
Correction, it looks like `karma-coverage-istanbul-reporter` has just released an updated version which uses latest istanbul libraries.

I still cannot provide direct support for karma plugins, one suggestion I have is to make sure you have only latest versions of the following libraries:
* istanbul-lib-instrument (4.x)
* istanbul-lib-coverage (3.x)
* istanbul-lib-source-maps (4.x)
* istanbul-lib-report (3.x)
* istanbul-reports (3.x)

You can check each by running `npm ls <package-name>`.  If your project installs only current versions of these libraries then I'd be interested in seeing a minimal reproduction repository.  If you have older versions of any of these packages you will need to eliminate them as they are known to experience this bug (karma-coverage 1.x will install older versions for example).
