### ISSUE TITLE
Coverage disappears unless I add a debug statement to the file

### ISSUE THREAD

**Issue by ezzatron** [istanbuljs/istanbuljs#238] opened 2018-11-15 00:39 UTC
I'm getting some very strange behaviour from my coverage report.

An entire file that I expected to be covered was missing from the coverage report, so I added a `console.trace()` statement to check if something weird was going on. All of a sudden, coverage results for the rest of the file magically appeared.

Here's the `nyc` command I'm using (broken up for readability):

```
NODE_ENV=test node_modules/.bin/nyc \
    --temp-dir artifacts/tests/coverage/nyc \
    --all \
    --include 'src/**/*.js*' \
    --extension .jsx \
    --require babel-register \
    --instrument false \
    --source-map false \
    node_modules/.bin/mocha 'test/suite/**/*.spec.*'
```

I'm also using `babel-plugin-istanbul` in my Babel configuration, as recommended by the docs.

I've been trying to create a small reproducible test case, but I'm not having much luck, and the project in which I'm experiencing this issue is closed-source, and can't be shared here, unfortunately.

Any ideas where to start in tracking down the cause of this bug?

**Comment by coreyfarrell** [comment] 2019-10-05 13:06
Sorry for missing this issue.  It's not possible for us to guess the cause without seeing a reproduction.  One suggestion I have is to try current versions of babel, babel-plugin-istanbul and nyc.  If you remove the `console.trace()` after seeing the coverage does this cause coverage to disappear again?  If so then you will need to pass `--cache=false` to nyc.

**Comment by coreyfarrell** [comment] 2020-04-14 13:25
Closing due to lack of required information.  Note that older versions of nyc / babel-plugin-istanbul are not supported.  Please try upgrading all babel / nyc / istanbul dependencies to latest versions, if you are still experiencing the issue you can open a new issue (please link reproduction).

**Closed by coreyfarrell** 2020-04-14 13:25 UTC
