### ISSUE TITLE
[istanbul-lib-coverage] Wrong "data" key in json report

### ISSUE THREAD

**Issue by emibloque** [istanbuljs/istanbuljs#458] opened 2019-08-08 10:58 UTC
## Summary

When using `jest` to run coverage and gather a json report, the report of files instrumented by jest is wrapped by a `"data"` key.

For example, in the following `coverage-final.json` the `.vue` file is instrumented directly by istanbul and the `.js` is instrumented by through jest. 
```
{"/.../src/containers/static-contact/Contact.vue": {"path":"/.../src/containers/static-contact/Contact.vue","statementMap":{"0":{"start":{"line":47,"column":0},"end":{"line":null,"column":-1}}},"fnMap":{},"branchMap":{},"s":{"0":1},"f":{},"b":{}}
,"/.../src/store/modules/modal.js": {"data":{"path":"/.../src/store/modules/modal.js","statementMap":{"0":{"start":{"line":1,"column":21},"end":{"line":40,"column":1}},"1":{"start":{"line":18,"column":6},"end":{"line":18,"column":34}},"2":{"start":{"line":22,"column":6},"end":{"line":22,"column":41}},"3":{"start":{"line":23,"column":6},"end":{"line":23,"column":62}},"4":{"start":{"line":24,"column":6},"end":{"line":24,"column":47}},"5":{"start":{"line":25,"column":6},"end":{"line":25,"column":49}},"6":{"start":{"line":26,"column":6},"end":{"line":26,"column":49}},"7":{"start":{"line":27,"column":6},"end":{"line":27,"column":55}},"8":{"start":{"line":33,"column":6},"end":{"line":33,"column":40}},"9":{"start":{"line":37,"column":6},"end":{"line":37,"column":42}}},"fnMap":{"0":{"name":"(anonymous_0)","decl":{"start":{"line":17,"column":21},"end":{"line":17,"column":22}},"loc":{"start":{"line":17,"column":41},"end":{"line":19,"column":5}},"line":17},"1":{"name":"(anonymous_1)","decl":{"start":{"line":21,"column":23},"end":{"line":21,"column":24}},"loc":{"start":{"line":21,"column":43},"end":{"line":28,"column":5}},"line":21},"2":{"name":"(anonymous_2)","decl":{"start":{"line":32,"column":21},"end":{"line":32,"column":22}},"loc":{"start":{"line":32,"column":46},"end":{"line":34,"column":5}},"line":32},"3":{"name":"(anonymous_3)","decl":{"start":{"line":36,"column":23},"end":{"line":36,"column":24}},"loc":{"start":{"line":36,"column":48},"end":{"line":38,"column":5}},"line":36}},"branchMap":{"0":{"loc":{"start":{"line":23,"column":35},"end":{"line":23,"column":62}},"type":"binary-expr","locations":[{"start":{"line":23,"column":35},"end":{"line":23,"column":53}},{"start":{"line":23,"column":57},"end":{"line":23,"column":62}}],"line":23},"1":{"loc":{"start":{"line":24,"column":29},"end":{"line":24,"column":47}},"type":"binary-expr","locations":[{"start":{"line":24,"column":29},"end":{"line":24,"column":41}},{"start":{"line":24,"column":45},"end":{"line":24,"column":47}}],"line":24},"2":{"loc":{"start":{"line":25,"column":30},"end":{"line":25,"column":49}},"type":"binary-expr","locations":[{"start":{"line":25,"column":30},"end":{"line":25,"column":43}},{"start":{"line":25,"column":47},"end":{"line":25,"column":49}}],"line":25},"3":{"loc":{"start":{"line":26,"column":30},"end":{"line":26,"column":49}},"type":"binary-expr","locations":[{"start":{"line":26,"column":30},"end":{"line":26,"column":43}},{"start":{"line":26,"column":47},"end":{"line":26,"column":49}}],"line":26},"4":{"loc":{"start":{"line":27,"column":33},"end":{"line":27,"column":55}},"type":"binary-expr","locations":[{"start":{"line":27,"column":33},"end":{"line":27,"column":49}},{"start":{"line":27,"column":53},"end":{"line":27,"column":55}}],"line":27}},"s":{"0":1,"1":1,"2":1,"3":1,"4":1,"5":1,"6":1,"7":1,"8":0,"9":0},"f":{"0":1,"1":1,"2":0,"3":0},"b":{"0":[1,1],"1":[1,1],"2":[1,1],"3":[1,1],"4":[1,1]},"_coverageSchema":"332fd63041d2c1bcb487cc26dd0d5f7d97098a6c","hash":"3018f72659512f478748c1d6b3200e824e3d60bb"}}
}
```

This problem is raised in this issue as well: https://github.com/facebook/jest/issues/2418#issuecomment-423806659

## Why this happen?

In my current scenario, `jest-cli` uses the `istanbul-lib-coverage` that it has within `node_modules/jest/node_modules/jest-cli/node_modules/istanbul-lib-coverage` directly to create `MappedCoverage` and `FileCoverage` objects, and after that it passes around the objects to `istanbul-lib-source-maps`, which also uses `istanbul-lib-coverage`, but the one within `node_modules/istanbul-lib-source-maps/node_modules/istanbul-lib-coverage`.

Because they are different files, the following `instanceof` check fails, and the `FileCoverage` objects fall in the next `else if`:

https://github.com/istanbuljs/istanbuljs/blob/90e60cc47833bb780680f916488ca24f0be36ca2/packages/istanbul-lib-coverage/lib/file.js#L160

I guess that in master the issue would be the same:
https://github.com/istanbuljs/istanbuljs/blob/025e8af619c2d20a7789b73d81c3c5f30441a129/packages/istanbul-lib-coverage/lib/file-coverage.js#L71

Therefore a new `FileCoverage` object is created with a `data` variable which it is another `FileCoverage`, that finally will be the one serialized when calling `toJSON`:
https://github.com/istanbuljs/istanbuljs/blob/90e60cc47833bb780680f916488ca24f0be36ca2/packages/istanbul-lib-coverage/lib/file.js#L248

## Proposed solution

I think that one solution would be to apply duck typing for this check. I can create a PR with the changes if you see it ok.

I'm able to reproduce and fix this in my current project modifying directly the files, but I don't know how to set up a test here to reproduce the issue, please let me know if you have any suggestion on how to set up a test for this.

**Comment by coreyfarrell** [comment] 2019-08-08 14:49
I question how/why you are getting multiple copies of istanbul-lib-coverage.  Generally jest should be deduplicating dependencies.  What version of jest are you using?  Can you link to a demo repository which includes a `package-lock.json`?

That said the file coverage data does not contain a data key so I think we could use that instead of the instanceof check.
```js
        if (typeof pathOrObj === 'string') {
            this.data = emptyCoverage(pathOrObj);
        } else if (typeof pathOrObj === 'object' && pathOrObj !== null) {
            if ('data' in pathOrObj) {
              this.data = pathOrObj.data;
            } else {
              this.data = pathOrObj;
            }
        } else {
            throw new Error('Invalid argument to coverage constructor');
        }
```
I haven't tested this yet, just an idea.

**Comment by emibloque** [comment] 2019-08-09 12:10
I should be doing something wrong then 😅
I'm going to recreate the issue in a new project with minimal setup and I'll get back in this issue when I have it.

**Comment by emibloque** [comment] 2019-08-13 14:04
#### Problem solved

I solved the issue I had in my project by removing `istanbul-lib-coverage` (I added it after following [this tutorial](https://glebbahmutov.com/blog/code-coverage-for-e2e-tests/), but it looks like it isn't needed in my current setup), so no problem at all if you want to close the issue.

#### Reproducing the issue

However, if you want to look more closely to this, I created [this repo](https://github.com/emibloque/istanbuljs-issue-458) with the issue just in case it helps troubleshooting this, or knowing if this is the expected behaviour with npm.

If you run the command `npm run test:cov` in [this commit](https://github.com/emibloque/istanbuljs-issue-458/commit/f79aed0966ae7ecc6f8ff49e611202d8a7cb971c), everything works perfect.
But when you add `istanbul-lib-coverage` (added in [this commit](https://github.com/emibloque/istanbuljs-issue-458/commit/bdf5bdde75b44b6e6edee2feb265285d26f4b329)), the `"data"` key appears in the coverage json.

Let me now if you want to continue looking into it and if I can help with anything!

Thank you very much for your time!

**Comment by coreyfarrell** [comment] 2019-08-13 14:12
The issue with the repo you linked is that you have a dependency on istanbul-lib-coverage@2.x, but your dependencies depend on istanbul-lib-coverage@1.x.  I'm guessing the 2.x module was not used but prevented the 1.x dependency from being deduped by `npm install`.  So I think this is still potentially an issue worth addressing, I'd like to leave this bug open as a reminder for me to create a PR.

**Comment by emibloque** [comment] 2019-08-13 14:21
Thanks for clarifying!
I will keep the repo in case it is needed in the future.

**Comment by coreyfarrell** [comment] 2019-08-13 14:46
No need to keep the repo if you don't want, the comments here are adequate to understand the root cause.

**Comment by mcblum** [comment] 2020-01-17 23:09
@coreyfarrell hey we're seeing a similar issue where we have an Angular 1 app along side an Angular 8 app and both Karma and Jest. Do you have any idea how we can solve this given that all of our files are in a monorepo?

**Comment by coreyfarrell** [comment] 2020-04-14 13:11
istanbul-lib-coverage@2 and istanbul-lib-coverage@3 cannot run together.  The latest version of karma-coverage and the latest version jest both use istanbul-lib-coverage@3 (the same as used by latest nyc).

I'm closing this issue as I believe it is resolved by updating to latest versions.

**Closed by coreyfarrell** 2020-04-14 13:11 UTC
