### ISSUE TITLE
Coverage Report Table has alignment issues on Terminus Terminal

### ISSUE THREAD

**Issue by JamieCorkhill** [istanbuljs/istanbuljs#440] opened 2019-07-05 07:54 UTC
I submitted this issue on the Jest Repository regarding the rendering of the coverage table but was told to post it here instead.

The issue is that on the Terminus Terminal for Windows, the columns of the generated table are not correctly aligned. They are correctly aligned, however, on the VS Code Integrated Terminal.

See [here](https://github.com/facebook/jest/issues/8646) for more details.

Thanks.

**Comment by coreyfarrell** [comment] 2019-07-05 12:54
This seems to me like a Terminus Terminal issue, it looks like maybe it's using a font that is not perfectly fixed width.

**Comment by JamieCorkhill** [comment] 2019-07-06 21:16
@coreyfarrell I might be wrong, but I'm using Fira Code, and I was under the impression it was monospaced: https://github.com/tonsky/FiraCode

**Comment by coreyfarrell** [comment] 2019-07-06 23:03
Judging from the images you posted it doesn't appear to be a different number of characters between the two images, just the alignment changes.  We don't use tabs in the reports to create indentation, it's spaces only so it seems like an issue with Terminus.

**Comment by coreyfarrell** [comment] 2019-10-05 12:35
If you're able to find more information feel free to comment but at this time I'm closing this issue as I believe the problem is elsewhere.  I'd recommend investigating the font used by your terminal, it needs to be fixed width for alignment of istanbul text reports to look correct.

**Closed by coreyfarrell** 2019-10-05 12:35 UTC
